version: '3.5'

services:
  postgres:
    container_name: atm_pg
    image: postgres
    environment:
      POSTGRES_USER: dmitrii
      POSTGRES_PASSWORD: 1111
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
